name: Build e Deploy

on:
  push:
    branches:
      - main


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurando o Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validar o Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Configurando o banco de dados
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: 'aulaDSC'
          postgresql user: 'postgres'
          postgresql password: 'root'
      - name: Permissão para executar o gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradlew
        run: ./gradlew build



